# Generated by Django 3.2.12 on 2023-08-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalRoad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_no', models.IntegerField(blank=True, db_column='S/No', null=True)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('county', models.TextField(blank=True, db_column='County', null=True)),
                ('sub_county', models.TextField(blank=True, db_column='Sub County', null=True)),
                ('name_of_site', models.TextField(blank=True, db_column='Name of Site', null=True)),
                ('dsh_category', models.TextField(blank=True, db_column='DSH Category', null=True)),
                ('type_of_site', models.TextField(blank=True, db_column='Type of site', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('no_of_aps', models.IntegerField(blank=True, db_column='No. of Aps', null=True)),
                ('date_surveyed', models.DateTimeField(blank=True, db_column='Date Surveyed', null=True)),
                ('date_installed', models.DateTimeField(blank=True, db_column='Date Installed', null=True)),
                ('contractor', models.TextField(blank=True, db_column='Contractor', null=True)),
                ('boq_amount', models.IntegerField(blank=True, db_column='BoQ Amount', null=True)),
                ('inspection_status', models.TextField(blank=True, db_column='Inspection status', null=True)),
                ('inspection_date', models.DateTimeField(blank=True, db_column='Inspection Date', null=True)),
            ],
            options={
                'db_table': 'Digital-road',
                'managed': False,
            },
        ),
    ]
